name: Sign and EX-Pack ( Linux )
description: Sign or Pack the .DEB .ZST(Arch) .RPM .TAR.GZ of Linux Package

inputs:
  gpg_key:
    required: true
  gpg_key_id:
    required: true
  out_path:
    required: true

runs:
  using: composite

  steps:
    - name: Package for Fedora
      working-directory: ${{ github.action_path }}/fedora
      shell: bash
      env:
        GPG_KEY: ${{ inputs.gpg_key }}
        GPG_KEY_ID: ${{ inputs.gpg_key_id }}
      run: |
        tree ${{ inputs.out_path }}/out
        mkdir ${{ github.workspace }}/tmp
        cp -a pkg.sh ${{ github.workspace }}/tmp
        docker build -f Dockerfile \
          --secret id=gpg_key,env=GPG_KEY \
          --secret id=gpg_key_id,env=GPG_KEY_ID \
          --output type=local,dest=${{ inputs.out_path }}/out/dist ${{ github.workspace }}
        rm -rf ${{ github.workspace }}/tmp

    - name: Package for Arch
      working-directory: ${{ github.action_path }}/arch
      shell: bash
      run: |
        tree ${{ inputs.out_path }}/out
        mkdir tmp
        cp pkg.sh ./tmp/
        cp ${{ inputs.out_path }}/build/PKGBUILD ./tmp/
        cp -a ${{ inputs.out_path }}/out/install/ ./tmp/install/
        docker build -f Dockerfile --output type=local,dest=${{ inputs.out_path }}/out/dist .
