name: Prepare the Tools ( Linux )
description: Prepare the Tools for CPack

runs:
  using: composite

  steps:
    - name: Prepare Tools
      shell: bash
      run: |
        sudo apt update
        sudo apt install tree -y
