name: Sign and EX-Pack
description: Sign software package and pack for Arch Linux

inputs:
  code_sign_key:
    required: true
  code_sign_crt:
    required: true
  pass:
    required: true
  gpg_key:
    required: true
  gpg_key_id:
    required: true
  out_path:
    required: true
  intermediate_crt:
    required: true

runs:
  using: composite

  steps:
    - name: Sign and EX-Pack ( Linux )
      if: runner.os == 'Linux'
      uses: RAT-ISET/release-action/pack/expack/linux@main
      with:
        gpg_key: ${{ inputs.gpg_key }}
        gpg_key_id: ${{ inputs.gpg_key_id }}
        out_path: ${{ inputs.out_path }}

    - name: Sign Software Package ( Windows )
      if: runner.os == 'Windows'
      uses: RAT-ISET/release-action/pack/expack/win@main
      with:
        code_sign_crt: ${{ inputs.code_sign_crt }}
        code_sign_key: ${{ inputs.code_sign_key }}
        intermediate_crt: ${{ inputs.intermediate_crt }}
        pass: ${{ inputs.pass }}
        out_path: ${{ inputs.out_path }}
